/*
 * Demo data generator.
 *
 *   npm run seed            → insert demo users + ~120 days of history if the ledger is empty
 *   npm run seed -- --reset → wipe operational collections first, then seed
 *
 * History is generated by replaying day-by-day events against an in-memory
 * stock map, so every stored quantity reconciles exactly with the ledger.
 */
const mongoose = require('mongoose');
const User = require('./models/User');
const Asset = require('./models/Asset');
const Purchase = require('./models/Purchase');
const Transfer = require('./models/Transfer');
const Assignment = require('./models/Assignment');
const Expenditure = require('./models/Expenditure');
const AuditLog = require('./models/AuditLog');
const { BASES } = require('./config/constants');

const DAY = 24 * 60 * 60 * 1000;
const HISTORY_DAYS = 120;

const DEMO_USERS = [
  { name: 'Col. Sarah Mitchell', email: 'admin@military.com', password: 'admin123', role: 'admin', base: 'Base Alpha' },
  { name: 'Lt. Col. James Carter', email: 'commander.alpha@military.com', password: 'commander123', role: 'base_commander', base: 'Base Alpha' },
  { name: 'Maj. Priya Raman', email: 'commander.bravo@military.com', password: 'commander123', role: 'base_commander', base: 'Base Bravo' },
  { name: 'Capt. Daniel Brooks', email: 'commander.charlie@military.com', password: 'commander123', role: 'base_commander', base: 'Base Charlie' },
  { name: 'Maj. Elena Novak', email: 'commander.delta@military.com', password: 'commander123', role: 'base_commander', base: 'Base Delta' },
  { name: 'Sgt. Ravi Kumar', email: 'logistics.alpha@military.com', password: 'logistics123', role: 'logistics_officer', base: 'Base Alpha' },
  { name: 'Sgt. Maria Lopez', email: 'logistics.bravo@military.com', password: 'logistics123', role: 'logistics_officer', base: 'Base Bravo' },
];

const CATALOG = [
  { name: 'Humvee M1151', assetType: 'vehicle', unitCost: 220000, initial: [8, 14], buy: [1, 3] },
  { name: 'MRAP Cougar 4x4', assetType: 'vehicle', unitCost: 475000, initial: [3, 6], buy: [1, 2] },
  { name: 'Light Utility Truck', assetType: 'vehicle', unitCost: 65000, initial: [10, 18], buy: [2, 4] },
  { name: 'M4A1 Carbine', assetType: 'weapon', unitCost: 1200, initial: [120, 220], buy: [20, 60] },
  { name: 'M249 Light Machine Gun', assetType: 'weapon', unitCost: 4100, initial: [15, 30], buy: [4, 10] },
  { name: 'M17 Pistol 9mm', assetType: 'weapon', unitCost: 580, initial: [60, 110], buy: [10, 30] },
  { name: '5.56mm NATO Rounds', assetType: 'ammunition', unitCost: 0.45, initial: [40000, 80000], buy: [10000, 30000] },
  { name: '9mm Parabellum Rounds', assetType: 'ammunition', unitCost: 0.3, initial: [15000, 30000], buy: [5000, 12000] },
  { name: '40mm Grenade Cartridge', assetType: 'ammunition', unitCost: 38, initial: [600, 1400], buy: [200, 500] },
  { name: 'Night Vision Goggles PVS-14', assetType: 'equipment', unitCost: 3500, initial: [40, 90], buy: [10, 25] },
  { name: 'Tactical Radio AN/PRC-152', assetType: 'equipment', unitCost: 6800, initial: [30, 60], buy: [6, 15] },
  { name: 'Body Armor IOTV', assetType: 'equipment', unitCost: 1600, initial: [100, 180], buy: [20, 50] },
];

const SUPPLIERS = ['Defense Logistics Agency', 'General Dynamics', 'AM General', 'Oshkosh Defense', 'L3Harris', 'Colt Defense', 'Olin Winchester'];
const PERSONNEL = [
  ['Pvt.', 'Arjun Mehta'], ['Cpl.', 'Liam O\'Connor'], ['Sgt.', 'Aisha Khan'], ['Pvt.', 'Noah Williams'], ['Spc.', 'Chen Wei'],
  ['Cpl.', 'Fatima Hassan'], ['Sgt.', 'Lucas Martin'], ['Pvt.', 'Sofia Rossi'], ['Spc.', 'Ethan Clarke'], ['Lt.', 'Meera Iyer'],
  ['Sgt.', 'Owen Davies'], ['Cpl.', 'Hana Suzuki'], ['Pvt.', 'Mateo Garcia'], ['Spc.', 'Grace Kim'], ['Lt.', 'Vikram Singh'],
];
const UNITS = ['1st Infantry Platoon', 'Recon Squad B', 'Motor Transport Section', 'Signals Detachment', 'Quick Reaction Force'];
const PURPOSES = ['Border patrol rotation', 'Field training exercise', 'Convoy escort', 'Perimeter security', 'Joint exercise', 'Reconnaissance mission'];

// Deterministic PRNG so every fresh seed produces the same story
const mulberry32 = (seed) => () => {
  seed |= 0; seed = (seed + 0x6d2b79f5) | 0;
  let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};

async function seedDemoData({ reset = false, log = console.log } = {}) {
  if (reset) {
    await Promise.all([Asset, Purchase, Transfer, Assignment, Expenditure, AuditLog].map((M) => M.deleteMany({})));
    await User.deleteMany({ email: { $in: DEMO_USERS.map((u) => u.email) } });
  }

  // Users: create any missing demo accounts (existing ones are left untouched)
  const users = {};
  for (const u of DEMO_USERS) {
    users[u.email] = (await User.findOne({ email: u.email })) || (await User.create(u));
  }

  const [purchaseCount, assetCount] = await Promise.all([Purchase.estimatedDocumentCount(), Asset.estimatedDocumentCount()]);
  if (purchaseCount > 0 || assetCount > 0) {
    log('ℹ️  Ledger already has data — skipping history seed (use --reset to rebuild).');
    return false;
  }

  const rand = mulberry32(20260926);
  const between = (lo, hi) => Math.floor(lo + rand() * (hi - lo + 1));
  const pickOne = (arr) => arr[Math.floor(rand() * arr.length)];
  const roundTo = (n, step) => Math.max(step, Math.round(n / step) * step);

  const admin = users['admin@military.com'];
  const commanderOf = Object.fromEntries(DEMO_USERS.filter((u) => u.role === 'base_commander').map((u) => [u.base, users[u.email]]));
  const logisticsOf = Object.fromEntries(DEMO_USERS.filter((u) => u.role === 'logistics_officer').map((u) => [u.base, users[u.email]]));
  const buyerFor = (base) => logisticsOf[base] || commanderOf[base] || admin;
  const stepFor = (item) => (item.assetType === 'ammunition' ? 100 : 1);

  // Asset lines: one per catalog item per base
  const assets = {};
  const key = (base, item) => `${base}|${item.name}`;
  for (const base of BASES) {
    for (const item of CATALOG) {
      assets[key(base, item)] = {
        _id: new mongoose.Types.ObjectId(), name: item.name, assetType: item.assetType, base,
        quantity: 0, unitCost: item.unitCost, description: '', purchasedBy: buyerFor(base)._id, isActive: true,
      };
    }
  }

  const rows = { purchases: [], transfers: [], assignments: [], expenditures: [], audit: [] };
  const audit = (at, actor, action, entity, entityId, base, summary, method, path) => rows.audit.push({
    user: actor._id, userName: actor.name, role: actor.role, base, action, entity, entityId: String(entityId), summary,
    method, path, statusCode: method === 'POST' ? 201 : 200, success: true, ip: '10.0.0.' + between(2, 250),
    userAgent: 'seed', durationMs: between(18, 140), createdAt: at,
  });
  const at = (dayOffset, hour = between(7, 19)) => {
    const d = new Date(Date.now() - dayOffset * DAY);
    d.setUTCHours(hour, between(0, 59), between(0, 59), 0);
    // Never generate events in the future for today's entries
    return d > Date.now() ? new Date(Date.now() - between(5, 240) * 60 * 1000) : d;
  };

  const purchase = (date, base, item, quantity) => {
    const a = assets[key(base, item)];
    const buyer = buyerFor(base);
    a.quantity += quantity;
    const p = {
      _id: new mongoose.Types.ObjectId(), asset: a._id, assetName: item.name, assetType: item.assetType, base, quantity,
      unitCost: item.unitCost, totalCost: Math.round(item.unitCost * quantity * 100) / 100, supplier: pickOne(SUPPLIERS),
      reference: `PO-${date.getUTCFullYear()}-${String(rows.purchases.length + 1001)}`, notes: '', purchaseDate: date,
      purchasedBy: buyer._id, createdAt: date, updatedAt: date,
    };
    rows.purchases.push(p);
    audit(date, buyer, 'PURCHASE_CREATE', 'Purchase', p._id, base, `Purchased ${quantity} × ${item.name} (${item.assetType}) for ${base}`, 'POST', '/api/purchases');
  };

  const activeAssignments = [];

  // Day 0 (≈120 days ago): initial stocking of every base
  for (const base of BASES) {
    for (const item of CATALOG) {
      purchase(at(HISTORY_DAYS, 9), base, item, roundTo(between(...item.initial), stepFor(item)));
    }
  }

  for (let day = HISTORY_DAYS - 1; day >= 0; day--) {
    for (const base of BASES) {
      const commander = commanderOf[base] || admin;

      // Replenishment purchases
      if (rand() < 0.22) {
        const item = pickOne(CATALOG);
        purchase(at(day), base, item, roundTo(between(...item.buy), stepFor(item)));
      }

      // Inter-base transfers
      if (rand() < 0.12) {
        const item = pickOne(CATALOG);
        const src = assets[key(base, item)];
        const toBase = pickOne(BASES.filter((b) => b !== base));
        const qty = roundTo(Math.floor(src.quantity * (0.05 + rand() * 0.12)), stepFor(item));
        if (qty >= 1 && qty <= src.quantity) {
          const date = at(day);
          const requestedByLogistics = logisticsOf[base] && rand() < 0.5;
          const requester = requestedByLogistics ? logisticsOf[base] : commander;
          const approvedAt = requestedByLogistics ? new Date(date.getTime() + between(1, 20) * 60 * 60 * 1000) : date;
          const rejected = requestedByLogistics && rand() < 0.12;
          const t = {
            _id: new mongoose.Types.ObjectId(), asset: src._id, assetName: item.name, assetType: item.assetType,
            fromBase: base, toBase, quantity: qty, transferredBy: requester._id,
            status: rejected ? 'rejected' : 'approved', approvedBy: commander._id, approvedAt,
            notes: pickOne(['Operational redeployment', 'Rebalancing stock levels', 'Support for joint exercise', 'Surge requirement']),
            decisionNote: rejected ? 'Stock required locally for upcoming exercise' : '',
            createdAt: date, updatedAt: approvedAt,
          };
          rows.transfers.push(t);
          if (requestedByLogistics) {
            audit(date, requester, 'TRANSFER_REQUEST', 'Transfer', t._id, base, `${qty} × ${item.name}: ${base} → ${toBase} (awaiting approval)`, 'POST', '/api/transfers');
          }
          if (!rejected) {
            src.quantity -= qty;
            assets[key(toBase, item)].quantity += qty;
          }
          audit(approvedAt, commander, requestedByLogistics ? (rejected ? 'TRANSFER_REJECT' : 'TRANSFER_APPROVE') : 'TRANSFER_EXECUTE',
            'Transfer', t._id, base, `${qty} × ${item.name}: ${base} → ${toBase}`, requestedByLogistics ? 'PUT' : 'POST', '/api/transfers');
        }
      }

      // Personnel assignments (weapons, equipment, vehicles)
      if (rand() < 0.35) {
        const item = pickOne(CATALOG.filter((c) => c.assetType !== 'ammunition'));
        const a = assets[key(base, item)];
        const qty = item.assetType === 'vehicle' ? 1 : between(1, item.assetType === 'weapon' ? 4 : 6);
        if (a.quantity >= qty) {
          const [rank, name] = pickOne(PERSONNEL);
          const date = at(day);
          a.quantity -= qty;
          const asg = {
            _id: new mongoose.Types.ObjectId(), asset: a._id, assetName: item.name, assetType: item.assetType,
            assignedTo: name, rank, serviceId: `SVC-${between(10000, 99999)}`, unit: pickOne(UNITS), base, quantity: qty,
            assignedBy: commander._id, purpose: pickOne(PURPOSES), assignedAt: date, status: 'active', closedAt: null, closedBy: null,
            createdAt: date, updatedAt: date,
          };
          rows.assignments.push(asg);
          activeAssignments.push(asg);
          audit(date, commander, 'ASSIGNMENT_CREATE', 'Assignment', asg._id, base, `Assigned ${qty} × ${item.name} to ${rank} ${name}`, 'POST', '/api/assignments');
        }
      }

      // Close out older assignments: most are returned, a few expended
      for (const asg of activeAssignments.filter((x) => x.base === base && x.status === 'active')) {
        const ageDays = (Date.now() - day * DAY - asg.assignedAt.getTime()) / DAY;
        if (ageDays > 7 && rand() < 0.06) {
          const date = at(day);
          const expended = rand() < 0.15;
          Object.assign(asg, { status: expended ? 'expended' : 'returned', closedAt: date, closedBy: commander._id, updatedAt: date });
          if (expended) {
            const reason = pickOne(['damaged', 'lost', 'combat']);
            const e = {
              _id: new mongoose.Types.ObjectId(), asset: asg.asset, assetName: asg.assetName, assetType: asg.assetType,
              quantity: asg.quantity, base, expendedBy: commander._id, reason, notes: `Expended by ${asg.rank} ${asg.assignedTo}`,
              assignment: asg._id, expendedAt: date, createdAt: date, updatedAt: date,
            };
            rows.expenditures.push(e);
            audit(date, commander, 'ASSIGNMENT_EXPEND', 'Expenditure', e._id, base, `${asg.quantity} × ${asg.assetName} assigned to ${asg.assignedTo} marked expended (${reason})`, 'PUT', '/api/assignments');
          } else {
            assets[`${base}|${asg.assetName}`].quantity += asg.quantity;
            audit(date, commander, 'ASSIGNMENT_RETURN', 'Assignment', asg._id, base, `${asg.assignedTo} returned ${asg.quantity} × ${asg.assetName}`, 'PUT', '/api/assignments');
          }
        }
      }

      // Direct expenditures: ammunition at training ranges, occasional equipment write-offs
      if (rand() < 0.3) {
        const ammo = rand() < 0.85;
        const item = pickOne(CATALOG.filter((c) => (ammo ? c.assetType === 'ammunition' : c.assetType === 'equipment')));
        const a = assets[key(base, item)];
        const qty = ammo ? roundTo(Math.floor(a.quantity * (0.02 + rand() * 0.05)), 100) : between(1, 3);
        if (qty >= 1 && qty <= a.quantity) {
          const date = at(day);
          const reason = ammo ? pickOne(['training', 'training', 'training', 'combat']) : pickOne(['damaged', 'maintenance', 'lost']);
          a.quantity -= qty;
          const e = {
            _id: new mongoose.Types.ObjectId(), asset: a._id, assetName: item.name, assetType: item.assetType, quantity: qty, base,
            expendedBy: commander._id, reason, notes: ammo ? 'Range qualification' : 'Written off after inspection',
            assignment: null, expendedAt: date, createdAt: date, updatedAt: date,
          };
          rows.expenditures.push(e);
          audit(date, commander, 'EXPENDITURE_CREATE', 'Expenditure', e._id, base, `Expended ${qty} × ${item.name} (${reason})`, 'POST', '/api/expenditures');
        }
      }
    }
  }

  // A few open requests so the approval workflow has something to show
  for (const [base, officer] of Object.entries(logisticsOf)) {
    for (const item of [CATALOG[3], CATALOG[9]]) {
      const src = assets[key(base, item)];
      const toBase = pickOne(BASES.filter((b) => b !== base));
      const qty = Math.max(1, Math.floor(src.quantity * 0.1));
      const date = at(between(0, 2));
      const t = {
        _id: new mongoose.Types.ObjectId(), asset: src._id, assetName: item.name, assetType: item.assetType, fromBase: base, toBase,
        quantity: qty, transferredBy: officer._id, status: 'pending', approvedBy: null, approvedAt: null,
        notes: 'Requested to support upcoming joint exercise', decisionNote: '', createdAt: date, updatedAt: date,
      };
      rows.transfers.push(t);
      audit(date, officer, 'TRANSFER_REQUEST', 'Transfer', t._id, base, `${qty} × ${item.name}: ${base} → ${toBase} (awaiting approval)`, 'POST', '/api/transfers');
    }
  }

  const now = new Date();
  await Asset.collection.insertMany(Object.values(assets).map((a) => ({ ...a, createdAt: at(HISTORY_DAYS, 9), updatedAt: now })));
  await Purchase.collection.insertMany(rows.purchases);
  await Transfer.collection.insertMany(rows.transfers);
  await Assignment.collection.insertMany(rows.assignments);
  if (rows.expenditures.length) await Expenditure.collection.insertMany(rows.expenditures);
  await AuditLog.collection.insertMany(rows.audit);

  log(`✅ Seeded ${Object.keys(assets).length} asset lines, ${rows.purchases.length} purchases, ${rows.transfers.length} transfers, ` +
      `${rows.assignments.length} assignments, ${rows.expenditures.length} expenditures, ${rows.audit.length} audit entries.`);
  return true;
}

module.exports = { seedDemoData, DEMO_USERS };

if (require.main === module) {
  require('dotenv').config();
  const connectDB = require('./config/db');
  connectDB()
    .then(() => seedDemoData({ reset: process.argv.includes('--reset') }))
    .then(() => mongoose.disconnect())
    .catch((err) => { console.error(err); process.exit(1); });
}
